# TODO: Move hardcoded values to values.yaml

{{- if .Values.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.tls.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.tls.secretName }}
  secretTemplate:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "dev,prod"  # Control destination namespaces
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "dev,prod" # Control auto-reflection namespaces
  duration: 8760h # 1 year
  renewBefore: 360h
  commonName: {{ .Values.tls.commonName }}
  dnsNames:
    - {{ .Values.tls.commonName }}
  issuerRef:
    name: self-signed
    kind: ClusterIssuer
  subject:
    organizations:
      - Bayazee GmbH
    countries:
      - DE
    organizationalUnits:
      - DevOps
    localities:
      - Berlin
    provinces:
      - Berlin
  usages:
    - digital signature
    - key encipherment
    - server auth

{{- end }}