
{{- if .Values.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.tls.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.tls.secretName }}
  duration: 8760h # 1 year
  renewBefore: 360h
  commonName: {{ .Values.tls.commonName }}
  dnsNames:
    - {{ .Values.tls.commonName }}
  issuerRef:
    name: self-signed
    kind: ClusterIssuer
  subject:
    organizations:
      - Bayazee GmbH
    countries:
      - DE
    organizationalUnits:
      - DevOps
    localities:
      - Berlin
    provinces:
      - Berlin
  usages:
    - digital signature
    - key encipherment
    - server auth
{{- end }}