# Prod environment values for the website Helm chart
environment: "prod"

replicaCount: 3

nameOverride: ""
fullnameOverride: ""

image:
  repository: bayazee/k8s-sample-app-website
  pullPolicy: IfNotPresent
  tag: "0.0.1"


service:
  type: ClusterIP
  port: 80

secretMessage: ""

ingress:
  path: /
  stripPrefix: false
  tls:
    secretName: website-tls