# Prod environment values for the website Helm chart
environment: "prod"

replicaCount: 3

nameOverride: ""
fullnameOverride: ""

# This docker image is same as the one used in the dev environment
# But it is already tested in lower environments and is ready for production
image:
  repository: bayazee/k8s-sample-app-website
  pullPolicy: IfNotPresent
  tag: "0.0.1"


service:
  type: ClusterIP
  port: 80

secretMessage: ""

ingress:
  path: /
  stripPrefix: false
  tls:
    secretName: website-tls

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi