# Dev environment values for the website Helm chart
environment: "dev"

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  repository: bayazee/k8s-sample-app-website
  pullPolicy: IfNotPresent
  tag: "0.0.1"


service:
  type: ClusterIP
  port: 80

secretMessage: ""

ingress:
  path: /dev
  stripPrefix: true
  tls:
    secretName: website-tls

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi