apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "website.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "website.labels" . | nindent 4 }}

spec:
    replicas: {{ .Values.replicaCount }}
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 0
    selector:
      matchLabels:
        app.kubernetes.io/name: {{ include "website.fullname" . }}
    template:
        metadata:
          annotations: 
            # This annotation is used to trigger a rolling update when the secret changes
            checksum/config: {{ .Values.secretMessage | sha256sum }}
          labels:
              {{- include "website.labels" . | nindent 14 }}
        spec:
            containers:
                - name: {{ include "website.fullname" . }}
                  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
                  imagePullPolicy: {{ .Values.image.pullPolicy }}
                  ports:
                    - name: http
                      containerPort: 80
                      protocol: TCP
                  env:
                    - name: ENVIRONMENT
                      value: {{ .Values.environment | quote }}
                    - name: SECRET_MESSAGE
                      valueFrom:
                        secretKeyRef:
                          name: {{ include "website.fullname" . }}-secret
                          key: secretMessage

                  # It is a static website, so we can use a simple liveness and readiness probe
                  # For a more complex application, you might want to use a more sophisticated health check
                  # like using failureThreshold and successThreshold
                  livenessProbe:
                    httpGet:
                      path: /
                      port: http
                    initialDelaySeconds: 5
                    periodSeconds: 10

                  readinessProbe:
                    httpGet:
                      path: /
                      port: http
                    initialDelaySeconds: 3
                    periodSeconds: 5
                  
                  resources:
                    {{- toYaml .Values.resources | nindent 20 }}
