apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "website.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "website.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`website.bayazee.com`) && PathPrefix(`{{ .Values.ingress.path}}`)
      kind: Rule
      services:
        - name: {{ include "website.fullname" . }}
          port: {{ .Values.service.port }}
      {{- if .Values.ingress.stripPrefix }}
      middlewares:
        - name: strip-prefix
          namespace: {{ .Release.Namespace }}
      {{- end }}
  tls:
    # This is the secret that contains the TLS certificate and key
    # It will automatically be created by cert-manager in its own namespace
    # and will be reflected to the current namespace
    secretName: {{ .Values.ingress.tls.secretName }}
    domains:
      - main: {{ .Values.ingress.tls.commonName }}