apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "website.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "website.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`{{ .Values.ingress.path}}`)
      kind: Rule
      services:
        - name: {{ include "website.fullname" . }}
          port: {{ .Values.service.port }}
      {{- if .Values.ingress.stripPrefix }}
      middlewares:
        - name: strip-dev
          namespace: {{ .Release.Namespace }}
      {{- end }}
  # Optionally add TLS + certResolver here