apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "website.fullname" . }}
  # namespace: dev
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/dev`)
      kind: Rule
      services:
        - name: {{ include "website.fullname" . }}
          port: {{ .Values.service.port }}
      middlewares:
        - name: strip-dev
          namespace: default
  # Optionally add TLS + certResolver here