{{- if .Values.ingress.stripPrefix -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-dev
  namespace: {{ .Release.Namespace }}
spec:
  stripPrefix:
    prefixes:
      - {{ .Values.ingress.path}}
{{- end }}