# For each environment, we will have path-based routing
# Before sending the request to the service, we will strip the prefix
{{- if .Values.ingress.stripPrefix -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "website.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - {{ .Values.ingress.path }}
{{- end }}