# This template defines a Kubernetes Secret to store sensitive information.
# Note: For production environments, consider using an external secret management solution.
# Ensure secrets are encrypted both at rest and in transit, with appropriate policies and access controls.
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "website.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "website.labels" . | nindent 4 }}
type: Opaque
stringData:
  secretMessage: {{ .Values.secretMessage | quote }}