apiVersion: v1
kind: Secret
metadata:
  name: {{ include "website.fullname" . }}-secret
  labels:
    app: {{ include "website.fullname" . }}
    chart: {{ include "website.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  secretMessage: {{ .Values.secretMessage | quote }}