apiVersion: v1
kind: Secret
metadata:
  name: {{ include "website.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "website.labels" . | nindent 4 }}
type: Opaque
stringData:
  secretMessage: {{ .Values.secretMessage | quote }}