apiVersion: v1
kind: Service
metadata:
  name: {{ include "website.fullname" . }}
  labels:
    app: {{ include "website.fullname" . }}
    chart: {{ include "website.chart" . }}
    release: {{ .Release.Name }}
spec:
    type: {{ .Values.service.type}}
    ports:
        - name: http
          port: {{ .Values.service.port }}
          targetPort: 80
    selector:
        app: {{ include "website.fullname" . }}
