apiVersion: v1
kind: Service
metadata:
  name: {{ include "website.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "website.labels" . | nindent 4 }}
spec:
    type: {{ .Values.service.type}}
    ports:
        - name: http
          port: {{ .Values.service.port }}
          targetPort: 80
    selector:
        app.kubernetes.io/name: {{ include "website.fullname" . }}
